# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9571a6451391efac1cfec6974bb1b6d4a9a21ddb9964f63a76b86b0bf54749c2c2c1f8af890a2bdb4ed363ba8af651445dcbd4d1d0107f72c7b78e2bbecc03a7

test:
  secret_key_base: 78462eefdeb596ab5870f6d72a274bab38641acb4bb8fa44ed7dbfceda3e65d44f7cc32e0ebe8f9c6e31717fd2eb88e2ab077333321600be189c4c58fdfa7398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
